// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package team4188_2014.subsystems;
import edu.wpi.first.wpilibj.CANJaguar;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.Timer;
//import edu.wpi.first.wpilibj.can.CANTimeoutException;
import team4188_2014.RobotMap;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import team4188_2014.commands.RetrieverDoNothing;
/**
 *
 */
public class Retriever extends Subsystem {
    private static final double PNEUMATIC_DELAY_SECONDS = 0.5;
    private static final double MAX_VOLT_RETRIEVER = 5.0;
    
    Compressor compressor = RobotMap.Compressor;
    DoubleSolenoid retrieverDoubleSolenoid = RobotMap.retrieverDoubleSolenoid;
    Relay retrieverSpike = RobotMap.retrieverRelay;
    DigitalInput retrieverOut = RobotMap.retrieverOut;
    DigitalInput retrieverIn = RobotMap.retrieverIn;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar ballCollect = RobotMap.retrieverballCollect;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    
    public void init(){
        retrieverSpike.set(Relay.Value.kOff);
        compressor.start();
        displayValues();
        doNothing();
    }
    
    public void initDefaultCommand() {
        setDefaultCommand(new RetrieverDoNothing());
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void retrieve(){
        retrieverSpike.set(Relay.Value.kForward);
    }
    
    public void eject(){
        retrieverSpike.set(Relay.Value.kReverse);
    }
    
    public void retractRetriever(){
        retrieverDoubleSolenoid.set(DoubleSolenoid.Value.kForward);    
        Timer.delay(PNEUMATIC_DELAY_SECONDS);
        retrieverDoubleSolenoid.set(DoubleSolenoid.Value.kOff);  
    }
    
    public void deployRetriever(){
        retrieverDoubleSolenoid.set(DoubleSolenoid.Value.kReverse);    
        Timer.delay(PNEUMATIC_DELAY_SECONDS);
        retrieverDoubleSolenoid.set(DoubleSolenoid.Value.kOff);  
    }
    
    public void doNothing(){
        retrieverSpike.set(Relay.Value.kOff);
    }
    
    public boolean isDeployed(){
        return retrieverOut.get();
    }
    
    public boolean isRetracted(){
        return retrieverIn.get();
    }
    
    public void displayValues(){
        SmartDashboard.putBoolean("retrieverIn", retrieverIn.get());
        SmartDashboard.putBoolean("retrieverOut", retrieverOut.get());
    }
         
    
}
