// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package team4188_2014.subsystems;
import team4188_2014.RobotMap;
import team4188_2014.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import team4188_2014.Robot;
/**
 *
 */
public class Shooter extends Subsystem {
    private static final double PNEUMATIC_DELAY_SECONDS = 0.2;
    private static final double GATE_DELAY_SECONDS = 0.2;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DoubleSolenoid shooterDoubleSolenoid = RobotMap.shooterDoubleSolenoid;
    Compressor compressor = RobotMap.Compressor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DoubleSolenoid gateDoubleSolenoid = RobotMap.shootergateDoubleSolenoid;
    DigitalInput gateLatch = RobotMap.shootergateLatch;
//    DigitalInput gateLatch2 = RobotMap.shootergateLatch2;
    DigitalInput shooterOut = RobotMap.shooterOut;
    DigitalInput shooterIn = RobotMap.shooterIn;
    DigitalInput gateLatchOut = RobotMap.gateLatchOut;
    DigitalInput gateLatchIn = RobotMap.gateLatchIn;
    
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new ShooterDoNothing());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void init(){
        compressor.start();
                
       // if(Robot.shooter.getGateLatch()) Robot.shooter.deployShooter();
       // if(!Robot.shooter.getGateLatch()) Robot.shooter.gateLatchReady();
    }
    
    public void retractShooter(){
        shooterDoubleSolenoid.set(DoubleSolenoid.Value.kForward);    
        Timer.delay(PNEUMATIC_DELAY_SECONDS);
        shooterDoubleSolenoid.set(DoubleSolenoid.Value.kOff); 
    }
    
    public void releaseTension(){
        shooterDoubleSolenoid.set(DoubleSolenoid.Value.kReverse);     
        Timer.delay(PNEUMATIC_DELAY_SECONDS);
        shooterDoubleSolenoid.set(DoubleSolenoid.Value.kOff);       
    }
    
    public void deployShooter(){   
//        gateDoubleSolenoid.set(DoubleSolenoid.Value.kReverse);
//        Timer.delay(GATE_DELAY_SECONDS);
//        gateDoubleSolenoid.set(DoubleSolenoid.Value.kOff);        
//        Timer.delay(GATE_DELAY_SECONDS);
        gateDoubleSolenoid.set(DoubleSolenoid.Value.kReverse);
        Timer.delay(GATE_DELAY_SECONDS);
        gateDoubleSolenoid.set(DoubleSolenoid.Value.kOff);
    }
    
    public void gateLatchReady(){
        gateDoubleSolenoid.set(DoubleSolenoid.Value.kForward);
        Timer.delay(GATE_DELAY_SECONDS);
        gateDoubleSolenoid.set(DoubleSolenoid.Value.kOff);
    }
    
    public void doNothing(){
        shooterDoubleSolenoid.set(DoubleSolenoid.Value.kOff);
    }
    
    public boolean getGateLatch(){
        return gateLatch.get() /**&& gateLatch2.get()**/;
    }
    
    public boolean isExtended(){
        return !shooterOut.get();
    }
    
    public boolean isRetracted(){
        return !shooterIn.get();
    }
    
    public boolean gateLatchExtended(){
        return !gateLatchOut.get();
    }       
    
    public boolean gateLatchRetracted(){
        return !gateLatchIn.get();
    }
    
    public boolean isCompressorEnabled() {
        return compressor.enabled();
    }    
    
    public void disableCompressor(){
        compressor.stop();
    }
    
    public void enableCompressor(){
        compressor.start();
    }
    
    public void delayForCount(int count){ 
        //determine an equation relating counts to seconds
        for (int i = count; i > 0; i--) Robot.shooter.doNothing();
    }
   
}
